#!/usr/bin/env bash

##
# Copyright (c) 2018 Samsung Electronics Co., Ltd. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##
# @file     pr-format-rpm-spec.sh
# @brief    Check the spec file (packaging/*.spec) with rpmlint command
# @see      https://github.com/nnsuite/TAOS-CI
# @author   Geunsik Lim <geunsik.lim@samsung.com>
#

# @brief [MODULE] TAOS/pr-format-rpm-spec
function pr-format-rpm-spec(){
    echo "########################################################################################"
    echo "[MODULE] TAOS/pr-format-rpm-spec: Check if a spec file is correctly written using rpmlint"
    spec_modified="false"
    # Inspect all *.patch files that are generated by "git show" command.
    FILELIST=`git show --pretty="format:" --name-only --diff-filter=AMRC`
    for i in ${FILELIST}; do
        if [[ $i =~ ^obsolete/.* ]]; then
            continue
        fi
        if [[ $i =~ ^external/.* ]]; then
            continue
        fi
        # Handle only spec file in case that there are lots of files in one commit.
        echo "[DEBUG] file name is ( $i )."
        RPM_SPEC_REPORT_FILE="rpm-spec-check-result.html"
        touch ../report/${RPM_SPEC_REPORT_FILE}
        echo "RPM spec checker is skipped because there is no spec file (e.g., *.spec) in this PR."
        if [[ `file $i | grep "ASCII text" | wc -l` -gt 0 ]]; then
            case $i in
                # in case of *.spec file
                *.spec )
                    echo "[DEBUG] ( $i ) file is source code with the text format."
                    rpmlint_result=`rpmlint $i | aha --line-fix > ../report/${RPM_SPEC_REPORT_FILE}`
                    echo "[DEBUG] rpmlint result:\n $rpmlint_result"
                    check_result="success"
                    spec_modified="true"
                    break
                    ;;
                * )
                    echo "[DEBUG] ( $i ) file is not source code with the text format."
                    check_result="success"
                    spec_modified="false"
                    ;;
            esac
        fi
    done
    
    # If developer(s) modify *.spec file, let's report an investigation result that checks common errors in the file.
    if [[ spec_modified == "true" ]]; then
    
        # Inform PR submitter of a hint in more detail to fix incorrect *.spec file.
        # TODO: Improve the existing handling method in case that developers incorrectly write *.spec file.
        message=":octocat: **cibot**: [FYI] We inform $user_id of a check result of spec file with rpmlint. If there are some warning(s) or error(s) in your spec file, modify ${i} correctly after reading the report at ${CISERVER}${PRJ_REPO_UPSTREAM}/ci/${dir_commit}/report/${RPM_SPEC_REPORT_FILE}."
        cibot_comment $TOKEN "$message" "$GITHUB_WEBHOOK_API/issues/$input_pr/comments"
    
        if [[ $check_result == "success" ]]; then
            echo "[DEBUG] Passed. the rpm spec checker."
            message="Successfully rpm spec checker is done."
            cibot_pr_report $TOKEN "success" "TAOS/pr-format-rpm-spec" "$message" "${CISERVER}${PRJ_REPO_UPSTREAM}/ci/${dir_commit}/" "${GITHUB_WEBHOOK_API}/statuses/$input_commit"
        else
            echo "[DEBUG] Failed. the rpm spec checker."
            message="Oooops. The rpm spec checker is failed."
            cibot_pr_report $TOKEN "failure" "TAOS/pr-format-rpm-spec" "$message" "${CISERVER}${PRJ_REPO_UPSTREAM}/ci/${dir_commit}/" "${GITHUB_WEBHOOK_API}/statuses/$input_commit"
        fi
    else
        echo "[DEBUG] Skipped. the rpm spec checker."
        message="Skipped. rpm spec checker is jumped because you did not modify a spec file."
        cibot_pr_report $TOKEN "success" "TAOS/pr-format-rpm-spec" "$message" "${CISERVER}${PRJ_REPO_UPSTREAM}/ci/${dir_commit}/" "${GITHUB_WEBHOOK_API}/statuses/$input_commit"
    
    fi
}

